### ISSUE TITLE
Lost settings, themes, packages with the recent update to v1.107.1

### ISSUE THREAD

**Issue by vimalkvn** [flathub/dev.pulsar_edit.Pulsar#17]
Hi, With the most recent update to v1.107.1, I've lost all my settings - key map, themes, and packages and had to redo all configuration. I'm using Flatpak 1.12.2 on Linux Mint 20.3.

If you need more information, I will be happy to provide. Thanks for your work!

**Comment by cat-master21** [comment]
Yes sorry about that, the Flatpak for Pulsar `$HOME/.pulsar` to inside the Flatpak (so when removing data that works and Gnome detects it as app data) so this separates the Flatpak version and any other installation. You can move/copy this to the new location.

**Comment by cat-master21** [comment]
@vimalkvn The new Pulsar data directory for the Flatpak version is `$HOME/.var/app/dev.pulsar_edit.Pulsar/data` so you can copy/move your configuratiom to there. I think this issue should be resolved now.

**Comment by vimalkvn** [comment]
Thank you @cat-master21.
