### ISSUE TITLE
Cant't execute Pulsar commands with the flatpak version

### ISSUE THREAD

**Issue by 5calV** [flathub/dev.pulsar_edit.Pulsar#23]
Hello!
For some reason I can not execute Pulsar commands in my terminal with the flatpak version installed.
Is this issue already known? Could this be a permission issue?
Flatpak Version: 1.110.0
Last update: 16th october 2023
Runtime: org.freedesktop.Sdk/x86_64/22.08
Distro: EndeavourOS with Gnome and XFCE
My Gnome session uses Wayland, my XFCE session uses X11/Xorg

**Comment by cat-master21** [comment]
Helo there @5calV, thanks for telling me about this issue. Currently Pulsar does not have the PPM installed in the users PATH (should apply to the DEB version also) and Pulsar is named `pulsar.sh`. Please see if https://github.com/flathub/dev.pulsar_edit.Pulsar/pull/24 fixes your issue.

**Comment by 5calV** [comment]
No, #24 did not fix the issue

**Comment by cat-master21** [comment]
Sorry @5calV I had not tested it before but the PR should be updated to actually include `ppm` & `apm` in the `PATH` so you can try installing Pulsar from #24 again.

**Comment by cat-master21** [comment]
Well @5calV I retested the PR, and it adds the commands `apm`, `ppm`, and `pulsar` into the (path of) shell but please feel free to open this issue if needed.
