### ISSUE TITLE
Does not allow reading/writing from removable storage

### ISSUE THREAD

**Issue by oneilmw** [flathub/dev.pulsar_edit.Pulsar#8]
Platform: Debian 12 (flatpak version)
Pulsar version: 1.105.0
The /media directory is not reachable, and devices mounted there are not available.  This holds true in the Project panel as well as the file manager launched through the app.  For me the file manager that it launches is Nemo.
This is a flatpak-exclusive bug.
Linux.pulsar_1.105.0_amd64.deb, the native Debian package, does not share this bug.

Currently I store all of my computer science projects on a removable USB drive.
Using the Flatpak version, I am incapable of loading those project files into Pulsar.
I am able to load the root directory (/) into the Pulsar project navigation panel.
However, the /media folder is missing, which is where removable devices are mounted by default.
The same is true with the file manager it launches. Currently it is using my default, nemo, though I doubt that's relevant, due to it likely propagating the issue from the permissions from the flatpak package itself.

source issue: [pulsar-edit/pulsar issue 589](https://github.com/pulsar-edit/pulsar/issues/589)

**Comment by oneilmw** [comment]
fixed #9 proposed

**Comment by cat-master21** [comment]
Thanks for proposing that, I will look at it soon.
